version: "3.7"

networks:
    localdev:
        name: localdev
        driver: bridge

services:
    catalog_api:
        container_name: api
        build:
            context: .
            dockerfile: containers/api/Dockerfile
        env_file: 
            - containers/api/.env
        networks: 
            - localdev
        ports:
            - 5000:5000
            - 5001:5001
        volumes:
            - ~/.aspnet/https:/https:ro
        depends_on:
            - mssql

    mssql:
        image: mssql
        container_name: mssql
        ports:
            - 1433:1433
        networks:
            - localdev

        